apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testjul30test-gitops
  description: This is GitOps manifest for testjul30test   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testjul30test
    janus-idp.io/tekton: testjul30test 
    backstage.io/kubernetes-id: testjul30test 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testjul30test
