apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: testjul30test-model-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  testjul30test-model-server
    app.kubernetes.io/part-of: testjul30test  
  name: testjul30test-model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  testjul30test-model-server 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  testjul30test-model-server
    spec:
      containers:
      - image: quay.io/rh-aiservices-bu/vllm-openai-ubi9:0.4.2
        args: [
            "--model",
            "",
            "--port",
            "8001",
            "--download-dir",
            "/models-cache",
            "--max-model-len",
            "4096"]
        resources:
          limits:
            nvidia.com/gpu: '1'
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: models-cache
          mountPath: /models-cache
        name: app-model-service
        ports:
        - containerPort: 8001
        securityContext:
          runAsNonRoot: true
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      - name: models-cache
        persistentVolumeClaim:
          claimName: testjul30test

      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
