apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testjul30test
  janus-idp.io/tekton: testjul30test
  backstage.io/kubernetes-id: testjul30test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testjul30test
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml