---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: testjul30test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testjul30test 
  name: testjul30test
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi